Comment entity configuration
MGQS-IT-Lab-and-Research-Center-Temp/IdealDiscuss pull request #107
Opened 2023-03-25 16:58 UTC by Akindats1

2023-03-25 19:48 UTC, absyinka reviewed
Remove the IsUnique() key from both userId and questionId as both are foreign keys respectively in the comment table

2023-03-25 20:02 UTC, absyinka requested changes
Also discard the changes on the appSetting.Development.json file

2023-03-28 08:40 UTC, Akindats1 commented
I have made the changes sir

2023-03-28 14:53 UTC, absyinka approved these changes

2023-03-28 14:53 UTC, merged