Added IQuestionReportRepository file and QuestionReportRepository file
MGQS-IT-Lab-and-Research-Center-Temp/IdealDiscuss pull request #14
Opened 2023-02-11 21:03 UTC by faranasj

2023-02-11 22:50 UTC, absyinka requested changes
Both interface and implementing class does not implement /inherit respective interface/class.

Do make changes as pointed above

2023-02-12 07:40 UTC, NurudeenAdeyemi reviewed
The interface class should inherit the IRepository with the type parameter replaced by the actual class. The implementation name is not correct and should also inherit the baseRepository and the Interface of its own as well as constructor injecting the context class

2023-02-12 07:44 UTC, NurudeenAdeyemi commented on Repository/Implementations/QuestionReportRepository.cs
> +    public class QuestionReport
This should be QuestionReportRepository

2023-02-12 07:44 UTC, NurudeenAdeyemi commented on Repository/Implementations/QuestionReportRepository.cs
> +    public class QuestionReport
and Inherit BaseRepository<QuestionReport>, IQuestionReportRepository

2023-02-12 07:44 UTC, NurudeenAdeyemi commented on Repository/Interfaces/IQuestionReportRepository.cs
> +    public interface IQuestionReportRepository
where is the class its inheriting

2023-02-12 07:53 UTC, faranasj reviewed
Please ignore this commit, I made a mistake

2023-02-12 08:28 UTC, NurudeenAdeyemi approved these changes

2023-02-12 08:30 UTC, absyinka approved these changes

2023-02-12 08:31 UTC, merged